# https://stackoverflow.com/questions/57150346/is-there-a-way-where-terraform-ignores-resourcenotfoundexception-and-destroys-th
# https://www.terraform.io/cli/commands/state/rm

########################################################################################
# This pipeline updates the terraform state file to match the the existing resources. 
# Useful when an azure resource is already deleted.
#
# terraform state rm <your_azure_resource>
########################################################################################

trigger:
- manual

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: 'stateRmENG'
  displayName: 'Terraform state rm ENG Shared-infra (Dev, QA, UAT, Pre)'
  type: boolean
  default: false
- name: 'stateRmPRO'
  displayName: 'Terraform state rm PRO Shared-infra (Production)'
  type: boolean
  default: false
- name: 'resourceAddress' 
  displayName: 'Terraform will search the state for any instances matching the given resource address, and remove the record of each one so that Terraform will no 
    longer be tracking the corresponding remote objects.'
  type: string
  default: 'module.us[0].<resource_name>.<resource_instance>'

# Define Variables for Environments
variables:
- template: configuration/shared-azure-devops-pipeline-vars.yml
- template: configuration/developbranch-service-connections.yml
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
  - template: configuration/mainbranch-service-connections.yml

stages: 
- stage: TerraformStateRmENG
  displayName: Terraform stateRmENG
  condition: ${{parameters.stateRmENG}}
  jobs:
    - template: templates/terraform-state-rm.yml
      parameters: 
        environment: ${{ variables.ENG_ENVIRONMENT }}
        SERVICE_CONNECTION_NAME_TFSTATE: ${{ variables.SERVICE_CONNECTION_NAME_TFSTATE }}
        RESOURCE_ADDRESS: ${{ parameters.resourceAddress }}
- stage: TerraformStateRmPRO
  displayName: Terraform stateRmPRO
  condition: ${{parameters.stateRmPRO}}
  jobs:
    - template: templates/terraform-state-rm.yml
      parameters: 
        environment: ${{ variables.PRO_ENVIRONMENT }}
        SERVICE_CONNECTION_NAME_TFSTATE: ${{ variables.SERVICE_CONNECTION_NAME_TFSTATE }}
        RESOURCE_ADDRESS: ${{ parameters.resourceAddress }}        