# File: templates/terraform-validate.yml 

parameters:
- name: 'environment'
  type: string
  default: 'dev'
- name: 'SERVICE_CONNECTION_NAME_TFSTATE'
  type: string
  default: 'svccon-app-analysis-dev'
- name: 'MONGODB_REPO'
  type: string  

jobs:
- job: TerraformValidateJob
  displayName: Validate
  continueOnError: false
  variables:
    - template: ../configuration/variable-group-with-secrets.yml
      parameters:
        environment: ${{ lower(parameters.environment) }}  
  steps:
  - bash: |
      echo "Build.SourceBranchName: $(Build.SourceBranchName)"
    displayName: 'show Build.SourceBranchName'
  - bash: |
      echo "GIT_BRANCH: $(GIT_BRANCH)"
    displayName: 'show GIT_BRANCH' 
  - checkout: self
    clean: true
  - checkout: ${{ PARAMETERS.MONGODB_REPO }}
    clean: true  
  - script: git config --system -l 
    displayName: git config system wide   
  - bash: env
    displayName: 'Show env' 
  - bash: |    
      echo "Bitbucket ref: $TOOLS_REF"    
    displayName: Bitbucket ref    # https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout
  - script: ls -la $(Build.SourcesDirectory)
    displayName: Show folders with multi repo checkouts
  - task: PublishPipelineArtifact@1
    displayName: Publish Artifacts
    inputs:
      targetPath: $(FOLDER_WITH_MONGODB_DATA)
      artifactName: $(ARTIFACTS_FOLDER_WITH_MONGODB_DATA)
      artifactType: 'pipeline'    
  - task: PublishPipelineArtifact@1
    displayName: Publish Artifacts
    inputs:
      targetPath: $(FOLDER_WITH_TERRAFORM_FILES)
      #artifact: $(ARTIFACTS_FOLDER_WITH_TERRAFORM_FILES)
      #publishLocation: 'pipeline'
      artifactName: $(ARTIFACTS_FOLDER_WITH_TERRAFORM_FILES)
      artifactType: 'pipeline'
  - task: TerraformInstaller@0
    displayName: Terraform Install
    inputs:
      terraformVersion: $(TERRAFORM_VERSION)
  - task: TerraformTaskV3@3
    displayName: Terraform Init
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: ${{ PARAMETERS.SERVICE_CONNECTION_NAME_TFSTATE }}
      backendAzureRmResourceGroupName: $(RESOURCE_GROUP_NAME_TERRAFORM_STATE)
      backendAzureRmStorageAccountName: $(STORAGE_ACCOUNT_NAME)
      backendAzureRmContainerName: $(CONTAINER_NAME)
      backendAzureRmKey: '$(INFRA_NAME)-$(GIT_BRANCH)branch-base.tfstate'
      workingDirectory: $(FOLDER_WITH_TERRAFORM_FILES)
  - task: TerraformTaskV3@3
    displayName: Terraform Validate
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: $(FOLDER_WITH_TERRAFORM_FILES)
