# APP
spring.main.web-application-type=none
applinkonpremise.name=@project.artifactId@
applinkonpremise.version=@project.version@

Core-Data.directory=Core-DataFiles
applinkonpremise.scheduling.enable=true

# Spring logging conf
logging.file.name=../Core-Data_router.log
logging.config=classpath:logback-spring.xml

# Configuration
applinkonpremise.configuration.watcher.rate=PT300S
applinkonpremise.configuration.watcher.initial-delay=PT60S
applinkonpremise.keystore.folder=${ALLUSERSPROFILE}/sanitization
applinkonpremise.keystore.name=keystore.p12
applinkonpremise.keystore.type=pkcs12
applinkonpremise.keystore.sanitization-alias=sanitization

# Storage-Node
applinkonpremise.Storage-Node.timeout=PT5S
applinkonpremise.Storage-Node.watcher.rate=PT300S
applinkonpremise.Storage-Node.watcher.initial-delay=PT80S

# Analysis
applinkonpremise.analysis.watcher.rate=PT600S
applinkonpremise.analysis.watcher.initial-delay=PT1S

scp.max.files.processed=50
applinkonpremise.Core-DataWeb-requests=true

# integration-service Cloud
applinkcloud.host=https://{environment}applinkcloud.azurewebsites.net/
applinkcloud.basepath=aets/{AETitle}/rs
applinkcloud.analysis.basepath=analysis/management/

# Azure login
azure.login.url=https://login.microsoftonline.com/{directoryId}/oauth2/v2.0/token
azure.login.directoryId=00000000-0000-0000-0000-000000000000
azure.login.clientId={clientId}
azure.login.grantType=client_credentials
azure.login.clientSecret={clientSecret}
azure.login.scope=api://00000000-0000-0000-0000-000000000000/.default

# Spring multipart files configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# Encryption properties
encrypt.iv=22,33,11,44,55,99,66,77,88,12,37,41,76,19,55,32
encrypt.algorithm=AES
encrypt.stringAlgorithm=AES/CBC/NoPadding


spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER